// Generated by CoffeeScript 1.8.0
(function() {
  var $, ResizeFont, td;

  $ = require('jquery');

  td = require('throttle-debounce');

  ResizeFont = (function() {
    "use strict";
    ResizeFont.prototype._defaults = {
      baseWidth: 640,
      delay: 300,
      type: 'debounce'
    };

    ResizeFont.prototype.resize = function() {
      var size, width;
      width = window.innerWidth;
      size = "" + (width / this.opts.baseWidth * 100) + "%";
      this.$body.css('font-size', size);
      return this;
    };

    function ResizeFont(opts) {
      this.opts = $.extend({}, this._defaults, opts);
      this.$body = $('body');
      this.resize();
      this.addEvent();
    }

    ResizeFont.prototype.addEvent = function() {
      $(window).on('resize.resizefont', td[this.opts.type](this.opts.delay, (function(_this) {
        return function() {
          return _this.resize();
        };
      })(this)));
      return this;
    };

    ResizeFont.prototype.rmEvent = function() {
      $(window).off('resize.resizefont');
      return this;
    };

    return ResizeFont;

  })();

  if (typeof define === 'function' && define.amd) {
    define(function() {
      return ResizeFont;
    });
  } else if (typeof module !== 'undefined' && module.exports) {
    module.exports = ResizeFont;
  } else {
    window.ResizeFont || (window.ResizeFont = ResizeFont);
  }

}).call(this);
