// Generated by CoffeeScript 1.9.0
(function() {
  var factory;

  (factory = function($, td) {
    "use strict";
    var ResizeFont;
    if (td === void 0) {
      td = $;
    }
    return ResizeFont = (function() {
      "use strict";
      ResizeFont.prototype._defaults = {
        baseWidth: 640,
        delay: 300,
        type: 'debounce'
      };

      ResizeFont.prototype.resize = function() {
        var size, width;
        width = window.innerWidth;
        size = (width / this.opts.baseWidth * 100) + "%";
        this.$body.css('font-size', size);
        return this;
      };

      function ResizeFont(opts) {
        this.opts = $.extend({}, this._defaults, opts);
        this.$body = $('body');
        this.resize();
        this.addEvent();
      }

      ResizeFont.prototype.addEvent = function() {
        $(window).on('resize.resizefont', td[this.opts.type](this.opts.delay, (function(_this) {
          return function() {
            return _this.resize();
          };
        })(this)));
        return this;
      };

      ResizeFont.prototype.rmEvent = function() {
        $(window).off('resize.resizefont');
        return this;
      };

      return ResizeFont;

    })();
  })((typeof window !== void 0 ? window : this), function() {
    if (typeof define === 'function' && define.amd) {
      define(factory(require('jquery'), require('throttle-debounce')));
    } else if (typeof module !== 'undefined' && module.exports) {
      module.exports = factory(require('jquery'), require('throttle-debounce'));
    } else {
      window.ResizeFont || (window.ResizeFont = factory(window.jQuery));
    }
  })();

}).call(this);
